### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Hikari-HN** [Lincoln-LM/sv-live-map#17]
Traceback (most recent call last):
  File "C:\Users\luqi1\Desktop\sv-live-map-master\main_gui.py", line 3, in <module>
    from sv_live_map_core.application import Application
  File "C:\Users\luqi1\Desktop\sv-live-map-master\sv_live_map_core\application.py", line 15, in <module>
    from sv_live_map_core.raid_reader import RaidReader
  File "C:\Users\luqi1\Desktop\sv-live-map-master\sv_live_map_core\raid_reader.py", line 5, in <module>
    from sv_live_map_core.nxreader import NXReader
  File "C:\Users\luqi1\Desktop\sv-live-map-master\sv_live_map_core\nxreader.py", line 8, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'

Solution：Add "pysub" in requirmement.txt.

**Comment by lincoln-lm** [comment]
odd, assumed pyusb was installed by default
