### ISSUE TITLE
Can't connect switch

### ISSUE THREAD

**Issue by BaiyuanLiu** [Lincoln-LM/sv-live-map#9]
Hi Lincoln, 
Thank you for your doing the live map, that's really interesting software for me. But I can't connect to my switch, by the way, I install the sys-botbase to my switch, and I can access the live-PkHex. When I try to click the connect it says:
1)connection timed out, the log writes: connected, unpack from requires a buffer of at least 1701539700 bytes for unpacking 4 bytes at offset 1701539696 ((actual buffer size is 12584)
2) if with click 'use cached tables', it will mention cached table./cached _tables/ONE_STAR.pkl does not exist. Indeed the ONE_STAR.pkl does not exist in the file. Would you help me solve these small issues? Thank you for your help and amazing work! 
Best Wishes

**Comment by lincoln-lm** [comment]
Are you on Scarlet or Violet? Latest version? Make sure you are fully in the game (able to move your character) before connecting and let me know if it will let you connect after a few reboots/restarting the game. I think one of the pointers I'm using for the new update isn't as stable as it could be, but if you get it to connect once you can check the "Use Cached Tables" box and it will skip the part of connection that is causing that error.

**Comment by BaiyuanLiu** [comment]
> 

Thank you for your reply. My game is Violet, the latest version 1.1.0. I can move my character and follow your guide to connect. But I still can't connect the switch. By the way, I used your SV-live map version from the bottom 'Windows Executable/ Direct Download'. Sorry, I don't have the python background knowledge. Please let me know of any potential method to solve this issues on my side. Thank you in advance! 
Best Wishes

**Comment by lincoln-lm** [comment]
You're still unable to connect even after restarting the console/restarting the game?

**Comment by BaiyuanLiu** [comment]
I just restart the switch, and opened the game, (re-extract the file) in the log it is mentioned below texts: 
Connected
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "customtkinter\widgets\ctk_button.py", line 377, in clicked
  File "main_gui.py", line 249, in toggle_connection
  File "main_gui.py", line 221, in connect
  File "sv_live_map_core\raid_reader.py", line 31, in __init__
  File "sv_live_map_core\raid_reader.py", line 96, in read_raid_enemy_table_arrays
  File "sv_live_map_core\raid_enemy_table_array.py", line 35, in __init__
  File "sv_live_map_core\flatbuffer_object.py", line 107, in read_init_object_array
  File "sv_live_map_core\flatbuffer_object.py", line 98, in read_object_array
  File "sv_live_map_core\raid_enemy_table_array.py", line 41, in __init__
  File "sv_live_map_core\flatbuffer_object.py", line 86, in read_init_object
  File "sv_live_map_core\flatbuffer_object.py", line 77, in read_object
  File "sv_live_map_core\raid_enemy_table_array.py", line 48, in __init__
  File "sv_live_map_core\flatbuffer_object.py", line 69, in read_init_int_enum
  File "sv_live_map_core\flatbuffer_object.py", line 56, in read_int_enum
  File "enum.py", line 695, in __call__
  File "enum.py", line 1111, in __new__
ValueError: 16 is not a valid Game

**Comment by BaiyuanLiu** [comment]
Hi Lincoln-LM, 

Great news for me. After I restart my game and switch a couple of times, the live map software connects the switch. All good! Thank you so much!
